name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox] # Run tests in both Chrome and Firefox

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests on ${{ matrix.browser }} # Runs tests in parallel for each browser
        run: npx cypress run --browser ${{ matrix.browser }} --headless

      - name: Upload Cypress results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/ # Upload videos
